### PR TITLE
documentElement, location, A, LINK, cloneNode implementation

### PR DESCRIPTION
**Pull request by Indomian**
Added new elements and implemented some DOM methods:
 - Added DocumentElement helper, providing shadowing of document.body and
   document.documentElement.body (if any). See test;
 - Added document.location element providing Location object manipulation;
 - Added HTMLLinkElement (partial implementation);
 - Added HTMLAnchorElement (partial implementation);
 - Added Node.cloneNode method (partial implementation);
 - Added Node.nodeValue member;
 - Added support for ID rules in querySelectors (#someid);
 - Added tests for new functions.

New dependencies:
 * urijs - for parsing URIs in Anchor and Location;
 * urlutils - for fast implementing of document.location interface;

Signed-off-by: Egor Bolgov <e.bolgov@semrush.com>

### CODE REVIEW

**Comment by christophehurpeau** [comment]
Thanks !
In the future, could you separate your PR please ? Would be easier to review :)

**Comment by Indomian** [comment]
Separate by functions or how? Problem that this functionality was created before merge of previous pull request so i made patch from diff and create commit.

**Comment by christophehurpeau** [comment]
By features, like each dot you have in the description, if possible :)

**Comment by Indomian** [comment]
Ok, I'll try that way in future. Could you please review and merge this for now?

**Comment by christophehurpeau** [comment]
Could you please review this PR ? https://github.com/christophehurpeau/html-document/pull/10/files

**Comment by Indomian** [comment]
@christophehurpeau - did check. Seems I should update my code to you libraries changes.

**Comment by Indomian** [comment]
Splitting this pull request on different pull request over current master branch.

**Pull request closed without merging**
