### PR TITLE
Updated getElementsByTagName so it searches deep.

### PR DESCRIPTION
**Pull request by Indomian**
Updated getElementsByTagName so it searches deep. Before it didn't find any elements in document 
because it checked only first depth level.

Signed-off-by: Egor Bolgov <e.bolgov@semrush.com>

### CODE REVIEW

**Comment by christophehurpeau** [comment]
Thanks ! Can you rebase or merge from master ?

**Comment by Indomian** [comment]
Sure

**Comment by Indomian** [comment]
Rebased on master. You can simply merge.

**Comment by Indomian** [comment]
Thank you!

**Pull request merged**
