### PR TITLE
Added support for document.location field processing.

### PR DESCRIPTION
**Pull request by Indomian**
Signed-off-by: Egor Bolgov <e.bolgov@semrush.com>

### CODE REVIEW

**Comment by christophehurpeau** [comment]
I don't see the point of implementing document.location.
Could you tell me your need for that ?

`html-document` is a lib to build html using DOM API, not reproducing a browser.
To simulate a browser, you could use [jsdom](https://www.npmjs.com/package/jsdom)

**Comment by Indomian** [comment]
I use html-document to provide testing enviroment for my application. So when i need document.location i added it. Also when you create **HTMLAnchorElement** it should use document.location to extend its' **href** member to full document URI.

**Comment by christophehurpeau** [comment]
Okay then.

However, how do you choose the packages ? urlutils is a bit old and the use of https://nodejs.org/api/url.html would be better from a lib
I searched for a few minutes but didn't found a valid candidate in this short time

**Comment by Indomian** [comment]
Well it was fast decision for my current purpose. It may be better to implement my own version of location realisation. I've chosen **urlutils** because it provides what I need and I spend on searching around 0.5 hour.

**Comment by Indomian** [comment]
I checked out [jsdom](https://www.npmjs.com/package/jsdom) - it is not good for my purposes. Style of your lib, for example:
```javascript
global.document = new Document();
...
delete global.document
```
is better for my purposes when dealing with tests. I can emulate enviroment, so my scripts pass normally.
Also checks [Url API](https://nodejs.org/api/url.html) - seems good, going to update code so it begin using internal library.

**Comment by Indomian** [comment]
Completely removed **urlutils** and **urijs**. Created own class based on [Url API](https://nodejs.org/api/url.html). Added tests, rebased over current master branch.

**Comment by christophehurpeau** [comment]
Thanks ! Can't merge

**Comment by Indomian** [comment]
Rebased over master.

**Comment by Indomian** [comment]
Thank you!

**Pull request merged**
